### ISSUE TITLE
0.44 a few major issues

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#542]
1. "Manual download" always crash the app.
2. Is it now necessary to always use the tiny menu to add new account in order to change the spoofed device? While it is nice to be able to change accounts without needing to login every time, the need to add a new one for every device seems to be a very very bad change. More time consuming, more taps, less easy.
2b. Device selection list cuts at the screen width, making it hard to know the full name of devices with long names. Old screen in Settings worked much better for this.
3. There is some minor transition issue on transition effects when opening an app page, eg a few elements/buttons showing before the page itself.
4. Does not show on the menu the name of the Yalp account the user is logged in.
5. Something useful would be allowing us to login with a chosen internal Yalp account, instead of a random one.
6. Does not work if user replace contemporary version with legacy, because some database depends on the version number and crash because "can not downgrade database version".

**Comment by yeriomin** [comment]
1. Fixed by https://github.com/yeriomin/YalpStore/commit/c827670c899664295ca3887c8a2198d813cabe7d.
2. This is a solution from [material design guidelines](https://material.io/design/components/navigation-drawer.html) and is also implemented in Play Store app. "the need to add a new one for every device" Only UI changed, all the work with google api is the same. Now the UI reflects the fact that every time you choose a new device to spoof a new account is used and a new device is created from scratch. Placing it in settings instead of the login dialog was a mistake. You are just used to the old UI ;)
2b. I'll see what I can do with the lack of screen space.
3. How do I reproduce it? What device are you using?
4. You mean "Built-in account" instead of a specific email belonging to Yalp Store? Why would a user need to know that? It is hidden intentionally.
5. No, it would not be useful. Yalp Store accounts are regularly disabled. Also, I need to have an ability to add new accounts without tagging a new Yalp Store version.
6. Both versions need to be available at the same time. If legacy and contemporary versions had the same version code, I would not be able to publish them both in F-Droid at the same time. Also, it has been like that for several versions already.

**Comment by Rikk** [comment]
2. Does it create entries in .xml config file for every one that's saved? This pollution wouldn't happen in previous versions. (Google's menu uses a single variable (email) for the drop-down list; here, we have two variables: email and device; therefore, I think the logic is not the same, even if you make the display similar.)
3. I will try to record screen at a later time.
4. It is useful to know the account so we can know if the same account was reused after we try to change it.
5. It would be useful because, contrarily to what happens in Play Store, with Yalp Store we need to change accounts to find which one has access to a newer update. Play Store checks for updates from all logged accounts at the same time. You know, Google doesn't push the same updates to all accounts at the same time.
6. Previous versions did not use a database, and both legacy and contemporary could work with the same configuration files.

**Comment by yeriomin** [comment]
1. Its out.
2. No, it doesn't. Pollution?.. In both cases "variables" are people/accounts. Do you really think the guidelines are for emails only?
3. Thanks.
4. It is a piece of internal logic that I would like to hide from the user.
5. The solution to this is just wait for a day or two. See FAQ. Also see 4.
6. I see. There is no point for the user to have both release versions. And if you are building your own version from source, flavor name is appended to applicationId which lets you have both installed at the same time.

**Comment by Rikk** [comment]
1\. Manual downloads still crash when opening from app list (long-press or menu in app line).

4\. What's the reason you want to hide it? The entire logic or the email accounts? I think you could mask the real email, so it shows a number only ("One", "Two", "Built-in Account 3", etc).
Hiding things is, perhaps, not the most well received action in open-source places, I guess.

5\. More often, it's about 1 week the rollout time for most Google apps, for example.
If there's a way to check all internal accounts at the same time, it would justify hiding all the names, because all would be be done together. In this case one profile (maybe it is a better name for the account + device + language combo) would enclose all internal account and the chosen device. However, I imagine the problem could be it sending too many requests to Google, right? But would it be done only once until the user log out, correct?

6\. My point is not having both at the same time, but being able to toggle between them if needed or wanted, without needing to delete or edit these new db manually. Naturally, this is not something Joe user will ever need to do.

------
7\. About version nomenclature, why do you need to append "-contemporary" to the main version? If the other one is "-legacy", then logically the first is the contemporary.

8\. It is needing automatic refresh of app page after account is changed.

9\. Usability suggestion: remember last selected language and device in New Account dialog (imo it could be named New Profile).
